/**
 * @file songs.ts
 * @description Database operations for the songs table.
 * 
 * This file contains all Supabase queries for:
 * - Fetching songs by ID
 * - Searching songs with fuzzy matching (Twi character normalization)
 * - Adding new songs to the database
 * 
 * The search functionality normalizes Twi special characters (ɛ→e, ɔ→o, ŋ→n)
 * so users can find songs even without a Twi keyboard.
 */

import { supabase, Song } from "./supabase";

/**
 * Normalizes Twi special characters for search matching.
 * This allows users to type "aseda" and find "asɛda".
 * 
 * Character mappings:
 * - ɛ, Ɛ → e
 * - ɔ, Ɔ → o
 * - ŋ, Ŋ → n
 * 
 * @param text - The text to normalize
 * @returns Normalized lowercase text with special characters replaced
 */
export function normalizeForSearch(text: string): string {
    return text
        .toLowerCase()
        .replace(/ɛ/g, "e")
        .replace(/Ɛ/g, "e")
        .replace(/ɔ/g, "o")
        .replace(/Ɔ/g, "o")
        .replace(/ŋ/g, "n")
        .replace(/Ŋ/g, "n");
}

/**
 * Fetches a single song by its ID.
 * 
 * @param id - The song ID to fetch
 * @returns The song object if found, null otherwise
 * 
 * @example
 * const song = await getSongById("1");
 * if (song) {
 *   console.log(song.title);
 * }
 */
export async function getSongById(id: string): Promise<Song | null> {
    const { data, error } = await supabase
        .from("songs")
        .select("*")
        .eq("id", parseInt(id))
        .single();

    if (error) {
        console.error("Error fetching song:", error);
        return null;
    }

    return data;
}

/**
 * Searches songs using the normalized search_text column.
 * Returns up to 20 results ordered by title.
 * 
 * The search is case-insensitive and matches partial text.
 * Twi characters are normalized (ɛ→e) for easier searching.
 * 
 * @param query - The search query string
 * @returns Array of matching songs (empty if none found or error)
 * 
 * @example
 * const results = await searchSongs("aseda");
 * // Will find songs with "asɛda" in title, artist, or lyrics
 */
export async function searchSongs(query: string): Promise<Song[]> {
    const normalizedQuery = normalizeForSearch(query);

    const { data, error } = await supabase
        .from("songs")
        .select("*")
        .ilike("search_text", `%${normalizedQuery}%`)
        .order("title")
        .limit(20);

    if (error) {
        console.error("Error searching songs:", error);
        return [];
    }

    return data || [];
}

/**
 * Searches songs for the suggestions dropdown (limited to 5 results).
 * Used by the SearchBar component for instant suggestions while typing.
 * 
 * @param query - The search query string
 * @returns Array of up to 5 matching songs
 */
export async function searchSongsSuggestions(query: string): Promise<Song[]> {
    const normalizedQuery = normalizeForSearch(query);

    const { data, error } = await supabase
        .from("songs")
        .select("*")
        .ilike("search_text", `%${normalizedQuery}%`)
        .order("title")
        .limit(5);

    if (error) {
        console.error("Error searching songs:", error);
        return [];
    }

    return data || [];
}

/**
 * Adds a new song to the database.
 * The song will be marked as unverified (is_verified: false) by default.
 * The search_text column is auto-generated by a database trigger.
 * 
 * @param song - The song data to insert
 * @param song.title - Song title (required)
 * @param song.artist - Artist name (optional)
 * @param song.lyrics - Full lyrics text (required)
 * @param song.language - Song language (e.g., "Twi", "English")
 * @returns Object with success status and optional error message
 * 
 * @example
 * const result = await addSong({
 *   title: "Aseda Yɛ Wo De",
 *   artist: "Daughters of Glorious Jesus",
 *   lyrics: "Verse 1:\nAseda yɛ wo de...",
 *   language: "Twi"
 * });
 * if (result.success) {
 *   console.log("Song added!");
 * }
 */
export async function addSong(song: {
    title: string;
    artist: string;
    lyrics: string;
    language: string;
}): Promise<{ success: boolean; error?: string }> {
    const { error } = await supabase.from("songs").insert([
        {
            title: song.title,
            artist: song.artist || null,
            lyrics: song.lyrics,
            language: song.language,
            is_verified: false,
        },
    ]);

    if (error) {
        console.error("Error adding song:", error);
        return { success: false, error: error.message };
    }

    return { success: true };
}

// Re-export Song type for convenience
export type { Song };
